# Generated by Django 6.0 on 2025-12-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Номер группы",
                "verbose_name_plural": "Номера группы",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Период",
                "verbose_name_plural": "Периоды",
            },
        ),
        migrations.CreateModel(
            name="StandardState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=10, unique=True)),
                ("name_en", models.CharField(max_length=50)),
                ("name_ru", models.CharField(max_length=50)),
                ("name_de", models.CharField(max_length=50)),
                ("name_la", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Стандартное состояние",
                "verbose_name_plural": "Стандартные состояния",
            },
        ),
        migrations.CreateModel(
            name="GroupElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("title_en", models.CharField(blank=True, max_length=100)),
                ("title_ru", models.CharField(blank=True, max_length=100)),
                ("title_de", models.CharField(blank=True, max_length=100)),
                (
                    "number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elements.groupnumber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Химическая группа",
                "verbose_name_plural": "Химические группы",
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atomic_number", models.PositiveSmallIntegerField(unique=True)),
                ("symbol", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("name_ru", models.CharField(blank=True, max_length=100)),
                ("name_de", models.CharField(blank=True, max_length=100)),
                ("atomic_mass", models.FloatField(blank=True, null=True)),
                (
                    "block",
                    models.CharField(
                        blank=True,
                        choices=[("s", "s"), ("p", "p"), ("d", "d"), ("f", "f")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("electron_configuration", models.CharField(blank=True, max_length=50)),
                ("density", models.FloatField(blank=True, null=True)),
                ("melting_point", models.FloatField(blank=True, null=True)),
                ("boiling_point", models.FloatField(blank=True, null=True)),
                ("oxidation_states", models.CharField(blank=True, max_length=100)),
                ("electronegativity_pauling", models.FloatField(blank=True, null=True)),
                ("color_hex", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elements.groupelement",
                    ),
                ),
                (
                    "group_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elements.groupnumber",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elements.period",
                    ),
                ),
                (
                    "standard_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elements.standardstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент",
                "verbose_name_plural": "Элементы",
                "ordering": ["atomic_number"],
            },
        ),
    ]
