# Generated by Django 6.0 on 2025-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atomic_number", models.PositiveSmallIntegerField(unique=True)),
                ("symbol", models.CharField(max_length=3, unique=True)),
                ("name_en", models.CharField(max_length=100)),
                ("name_ru", models.CharField(blank=True, max_length=100)),
                ("name_de", models.CharField(blank=True, max_length=100)),
                (
                    "atomic_mass",
                    models.FloatField(
                        blank=True, help_text="Standard atomic weight (u)", null=True
                    ),
                ),
                ("period", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("group", models.CharField(blank=True, max_length=10, null=True)),
                ("block", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="metal / nonmetal / metalloid / noble gas / lanthanoid / actinoid",
                        max_length=50,
                    ),
                ),
                (
                    "density",
                    models.FloatField(
                        blank=True,
                        help_text="g/cm^3 at 20°C (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "melting_point",
                    models.FloatField(blank=True, help_text="°C", null=True),
                ),
                (
                    "boiling_point",
                    models.FloatField(blank=True, help_text="°C", null=True),
                ),
                ("oxidation_states", models.CharField(blank=True, max_length=100)),
                ("electronegativity_pauling", models.FloatField(blank=True, null=True)),
                ("color_hex", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
                "ordering": ["atomic_number"],
            },
        ),
    ]
