# Generated by Django 5.2.6 on 2025-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnumber',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='groupnumber',
            name='name_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='groupnumber',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='groupnumber',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
