# Generated by Django 6.0 on 2025-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="element",
            name="name_en",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
