# Generated by Django 6.0 on 2025-12-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("standards", "0005_alter_basestandard_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ISO15608Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO/TR 15608 group code", max_length=10, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Группа материала ISO/TR 15608",
                "verbose_name_plural": "Группы материалов ISO/TR 15608",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key, e.g. austenitic, duplex",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Категория материала",
                "verbose_name_plural": "Категории материалов",
                "ordering": ("sort_order", "key"),
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_number",
                    models.CharField(
                        help_text="DIN EN 10027-2 number, e.g. 1.4571",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "main_group",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Steel, 2 = Heavy metals, 3 = Light metals"
                    ),
                ),
                (
                    "steel_group_en10020",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="40–49 according to DIN EN 10020 (only for steels)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "iso_15608_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="materials.iso15608group",
                    ),
                ),
                (
                    "material_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="materials.materialcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ("material_number",),
            },
        ),
        migrations.CreateModel(
            name="MaterialEquivalent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(help_text="e.g. AISI 316L", max_length=100),
                ),
                (
                    "equivalence_type",
                    models.CharField(
                        choices=[
                            ("equivalent", "Equivalent"),
                            ("approximate", "Approximate"),
                            ("comparable", "Comparable"),
                        ],
                        default="equivalent",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equivalents",
                        to="materials.material",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_equivalents",
                        to="standards.standardedition",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "standard", "designation")},
            },
        ),
        migrations.CreateModel(
            name="MaterialSymbolicName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="e.g. X6CrNiMoTi17-12-2", max_length=100
                    ),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbolic_names",
                        to="materials.material",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="symbolic_materials",
                        to="standards.standardedition",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "symbol")},
            },
        ),
    ]
