# Generated by Django 6.0 on 2025-12-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("elements", "0002_groupnumber_name_groupnumber_name_de_and_more"),
        ("standards", "0005_alter_basestandard_number_and_more"),
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatTreatmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="annealing, quenching, tempering, solution_annealing",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тип термообработки",
                "verbose_name_plural": "Типы термообработки",
                "ordering": ("sort_order", "key"),
            },
        ),
        migrations.CreateModel(
            name="ISO15608Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO/TR 15608 group code", max_length=10, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Группа материала ISO/TR 15608",
                "verbose_name_plural": "Группы материалов ISO/TR 15608",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable key, e.g. austenitic, duplex",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Категория материала",
                "verbose_name_plural": "Категории материалов",
                "ordering": ("sort_order", "key"),
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_number",
                    models.CharField(
                        help_text="DIN EN 10027-2 number, e.g. 1.4571",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "main_group",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Steel, 2 = Heavy metals, 3 = Light metals"
                    ),
                ),
                (
                    "steel_group_en10020",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="40–49 according to DIN EN 10020 (only for steels)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "iso_15608_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="materials.iso15608group",
                    ),
                ),
                (
                    "material_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="materials.materialcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ("material_number",),
            },
        ),
        migrations.CreateModel(
            name="MaterialChemicalComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_compositions",
                        to="materials.material",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        help_text="Standard defining chemical composition",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="standards.standardedition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Химический состав материала",
                "verbose_name_plural": "Химические составы материалов",
                "unique_together": {("material", "standard")},
            },
        ),
        migrations.CreateModel(
            name="MaterialHeatTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=True, help_text="Recommended / typical heat treatment"
                    ),
                ),
                (
                    "heat_treatment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_heat_treatments",
                        to="materials.heattreatmenttype",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_treatments",
                        to="materials.material",
                    ),
                ),
                (
                    "standard_edition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard defining this heat treatment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="standards.standardedition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Термообработка материала",
                "verbose_name_plural": "Термообработки материалов",
                "unique_together": {
                    ("material", "heat_treatment_type", "standard_edition")
                },
            },
        ),
        migrations.CreateModel(
            name="HeatTreatmentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.PositiveSmallIntegerField()),
                ("temperature_min", models.FloatField(blank=True, null=True)),
                ("temperature_max", models.FloatField(blank=True, null=True)),
                ("time_min", models.FloatField(blank=True, null=True)),
                ("time_max", models.FloatField(blank=True, null=True)),
                (
                    "cooling_medium",
                    models.CharField(
                        blank=True, help_text="water, oil, air, furnace", max_length=50
                    ),
                ),
                (
                    "temperature_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
                (
                    "time_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
                (
                    "heat_treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="materials.materialheattreatment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг термообработки",
                "verbose_name_plural": "Шаги термообработки",
                "ordering": ("step_order",),
            },
        ),
        migrations.CreateModel(
            name="MaterialMechanicalPropertySet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_min", models.FloatField(blank=True, null=True)),
                ("temperature_max", models.FloatField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                    ),
                ),
                (
                    "standard_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="standards.standardedition",
                    ),
                ),
                (
                    "temperature_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор механических свойств",
                "verbose_name_plural": "Наборы механических свойств",
            },
        ),
        migrations.CreateModel(
            name="MaterialPhysicalPropertySet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_min", models.FloatField(blank=True, null=True)),
                ("temperature_max", models.FloatField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.material",
                    ),
                ),
                (
                    "standard_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="standards.standardedition",
                    ),
                ),
                (
                    "temperature_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор физических свойств",
                "verbose_name_plural": "Наборы физических свойств",
            },
        ),
        migrations.CreateModel(
            name="MechanicalPropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="units.unit"
                    ),
                ),
                (
                    "physical_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="units.physicalquantity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип механического свойства",
                "verbose_name_plural": "Типы механических свойств",
            },
        ),
        migrations.CreateModel(
            name="PhysicalPropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("symbol", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="units.unit"
                    ),
                ),
                (
                    "physical_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="units.physicalquantity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип физического свойства",
                "verbose_name_plural": "Типы физических свойств",
            },
        ),
        migrations.CreateModel(
            name="MaterialChemicalElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.FloatField(default=0.0)),
                ("max_value", models.FloatField()),
                (
                    "composition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="materials.materialchemicalcomposition",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="elements.element",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        limit_choices_to={"key": "percent"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Химический элемент",
                "verbose_name_plural": "Химические элементы",
                "unique_together": {("composition", "element")},
            },
        ),
        migrations.CreateModel(
            name="MaterialEquivalent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(help_text="e.g. AISI 316L", max_length=100),
                ),
                (
                    "equivalence_type",
                    models.CharField(
                        choices=[
                            ("equivalent", "Equivalent"),
                            ("approximate", "Approximate"),
                            ("comparable", "Comparable"),
                        ],
                        default="equivalent",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equivalents",
                        to="materials.material",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_equivalents",
                        to="standards.standardedition",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "standard", "designation")},
            },
        ),
        migrations.CreateModel(
            name="MaterialSymbolicName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="e.g. X6CrNiMoTi17-12-2", max_length=100
                    ),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbolic_names",
                        to="materials.material",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="symbolic_materials",
                        to="standards.standardedition",
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "standard", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="MaterialMechanicalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="units.unit"
                    ),
                ),
                (
                    "property_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="materials.materialmechanicalpropertyset",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.mechanicalpropertytype",
                    ),
                ),
            ],
            options={
                "unique_together": {("property_set", "property_type")},
            },
        ),
        migrations.CreateModel(
            name="MaterialPhysicalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="units.unit"
                    ),
                ),
                (
                    "property_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="materials.materialphysicalpropertyset",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.physicalpropertytype",
                    ),
                ),
            ],
            options={
                "unique_together": {("property_set", "property_type")},
            },
        ),
    ]
