# Generated by Django 6.0 on 2025-12-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "key"),
            },
        ),
        migrations.CreateModel(
            name="MaterialAnalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_material_code", models.CharField(max_length=50)),
                ("to_material_code", models.CharField(max_length=50)),
                (
                    "equivalence_type",
                    models.CharField(
                        choices=[
                            ("equivalent", "Equivalent"),
                            ("comparable", "Comparable"),
                            ("approximate", "Approximate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "from_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analogues_from",
                        to="materials.standardsystem",
                    ),
                ),
                (
                    "to_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analogues_to",
                        to="materials.standardsystem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="standard_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="materials.standardsystem",
                null=True,
                blank=True,
            ),
        ),
        migrations.CreateModel(
            name="ASMEMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specification", models.CharField(max_length=20)),
                ("grade", models.CharField(max_length=50)),
                ("uns_number", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "standard_system",
                    models.ForeignKey(
                        limit_choices_to={"key": "ASME"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.standardsystem",
                    ),
                ),
            ],
            options={
                "unique_together": {("specification", "grade")},
            },
        ),
    ]
