# Generated by Django 6.0 on 2025-12-28 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0002_standardsystem_materialanalogue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialanalogue",
            options={
                "verbose_name": "Аналог материала",
                "verbose_name_plural": "Аналоги материалов",
            },
        ),
        migrations.AlterModelOptions(
            name="standardsystem",
            options={
                "ordering": ("sort_order", "key"),
                "verbose_name": "Система стандартов",
                "verbose_name_plural": "Системы стандартов",
            },
        ),
    ]
