# Generated by Django 6.0 on 2025-12-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("title_en", models.CharField(max_length=500)),
                ("title_ru", models.CharField(blank=True, max_length=500)),
                ("title_de", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="StandardOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_ru", models.CharField(blank=True, max_length=200)),
                ("name_de", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Организация стандартизации",
                "verbose_name_plural": "Организации стандартизации",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StandardEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="standards.basestandard",
                    ),
                ),
            ],
            options={
                "ordering": ["base_standard", "-year"],
            },
        ),
        migrations.CreateModel(
            name="StandardEditionOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edition_orgs",
                        to="standards.standardedition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standards.standardorganization",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("edition", "organization")},
            },
        ),
        migrations.AddField(
            model_name="standardedition",
            name="organizations",
            field=models.ManyToManyField(
                through="standards.StandardEditionOrganization",
                to="standards.standardorganization",
            ),
        ),
        migrations.CreateModel(
            name="StandardSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("title_en", models.CharField(blank=True, max_length=300)),
                ("title_ru", models.CharField(blank=True, max_length=300)),
                ("title_de", models.CharField(blank=True, max_length=300)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="standards.standardorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серия стандартов",
                "verbose_name_plural": "Серии стандартов",
                "ordering": ["organization__code", "code"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.AddField(
            model_name="basestandard",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_standards",
                to="standards.standardseries",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="standardedition",
            unique_together={("base_standard", "year")},
        ),
        migrations.CreateModel(
            name="StandardPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name_en", models.CharField(blank=True, max_length=300)),
                ("name_ru", models.CharField(blank=True, max_length=300)),
                ("name_de", models.CharField(blank=True, max_length=300)),
                (
                    "base_standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="standards.basestandard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часть стандарта",
                "verbose_name_plural": "Части стандарта",
                "ordering": ["base_standard", "code"],
                "unique_together": {("base_standard", "code")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="basestandard",
            unique_together={("series", "number")},
        ),
    ]
