# Generated by Django 6.0 on 2025-12-21 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basestandard",
            options={
                "verbose_name": "Базовый стандарт",
                "verbose_name_plural": "Базовые стандарты",
            },
        ),
        migrations.AlterModelOptions(
            name="standardedition",
            options={
                "ordering": ["base_standard", "-year"],
                "verbose_name": "Редакция стандарта",
                "verbose_name_plural": "Редакции стандартов",
            },
        ),
    ]
