# Generated by Django 6.0 on 2025-12-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standards", "0002_alter_basestandard_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardseries",
            name="separator",
            field=models.CharField(
                default="-",
                help_text="Разделитель между серией и номером ('.' или '-')",
                max_length=1,
            ),
        ),
    ]
