# Generated by Django 6.0 on 2025-12-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standards", "0003_standardseries_separator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardseries",
            name="separator",
        ),
        migrations.AddField(
            model_name="basestandard",
            name="separator",
            field=models.CharField(
                default="-",
                help_text="Разделитель между серией и номером ('.' или '-')",
                max_length=1,
            ),
        ),
    ]
