# Generated by Django 6.0 on 2025-12-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standards", "0004_remove_standardseries_separator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basestandard",
            name="number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="basestandard",
            name="separator",
            field=models.CharField(
                blank=True,
                default="-",
                help_text="Разделитель между серией и номером ('.' или '-')",
                max_length=1,
                null=True,
            ),
        ),
    ]
