# Generated by Django 6.0 on 2025-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO language code, e.g. en, ru, de",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable language name", max_length=100
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        blank=True,
                        help_text="Language name in its own language",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is language available for selection"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default system language"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ordering in UI"
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "ordering": ["sort_order", "code"],
            },
        ),
    ]
