# Generated by Django 6.0 on 2025-12-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("language", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="language",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID объекта")),
                (
                    "field",
                    models.CharField(
                        help_text="Translated field name (name, description, title, etc.)",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Модель",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="language.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод",
                "verbose_name_plural": "Переводы",
                "ordering": ["content_type", "object_id", "field", "language"],
                "unique_together": {("content_type", "object_id", "field", "language")},
            },
        ),
    ]
