# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhysicalQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name_en", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100)),
                ("name_de", models.CharField(max_length=100)),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Common symbol, e.g. L, p, T",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Физическая величина",
                "verbose_name_plural": "Физические величины",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30)),
                ("symbol", models.CharField(max_length=20)),
                ("name_en", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100)),
                ("name_de", models.CharField(max_length=100)),
                ("is_base", models.BooleanField(default=False)),
                (
                    "factor",
                    models.FloatField(
                        default=1.0, help_text="Multiplier to convert to base unit"
                    ),
                ),
                (
                    "offset",
                    models.FloatField(
                        default=0.0, help_text="Offset added after multiplication"
                    ),
                ),
                (
                    "quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="units.physicalquantity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
                "unique_together": {("quantity", "key")},
            },
        ),
    ]
